import { Schema, Table, Column, ColumnType } from '@powersync/web';

export const AppSchema = new Schema([
  new Table('patients', [
    new Column('name', ColumnType.Text),
    new Column('ward_number', ColumnType.Text),
    new Column('age', ColumnType.Integer),
    new Column('gender', ColumnType.Text),
    new Column('category', ColumnType.Text),
    new Column('past_surgeries', ColumnType.Text),
    new Column('chronic_diseases', ColumnType.Text),
    new Column('psych_drugs', ColumnType.Text),
    new Column('medical_drugs', ColumnType.Text),
    new Column('allergies', ColumnType.Text),
    new Column('er_admission_date', ColumnType.Text),
    new Column('er_admission_doctor', ColumnType.Text),
    new Column('er_chief_complaint', ColumnType.Text),
    new Column('er_treatment', ColumnType.Text),
    new Column('created_at', ColumnType.Text),
    new Column('updated_at', ColumnType.Text),
  ]),
  new Table('visits', [
    new Column('patient_id', ColumnType.Text),
    new Column('doctor_id', ColumnType.Text),
    new Column('visit_date', ColumnType.Text),
    new Column('exam_notes', ColumnType.Text),
  ]),
  new Table('investigations', [
    new Column('patient_id', ColumnType.Text),
    new Column('date', ColumnType.Text),
    new Column('wbc', ColumnType.Real),
    new Column('hb', ColumnType.Real),
    new Column('s_urea', ColumnType.Real),
    new Column('s_creatinine', ColumnType.Real),
    new Column('ast', ColumnType.Real),
    new Column('alt', ColumnType.Real),
    new Column('tsb', ColumnType.Real),
    new Column('hba1c', ColumnType.Real),
    new Column('rbs', ColumnType.Real),
    new Column('is_er', ColumnType.Integer),
    new Column('doctor_id', ColumnType.Text),
    new Column('doctor_name', ColumnType.Text),
  ]),
  new Table('user_profiles', [
    new Column('user_id', ColumnType.Text),
    new Column('ward_name', ColumnType.Text),
    new Column('offline_mode_enabled', ColumnType.Integer),
    new Column('is_admin', ColumnType.Integer),
    new Column('ai_enabled', ColumnType.Integer),
    new Column('created_at', ColumnType.Text),
    new Column('updated_at', ColumnType.Text),
  ]),
  new Table('system_settings', [
    new Column('global_offline_enabled', ColumnType.Integer),
    new Column('updated_at', ColumnType.Text),
  ])
]);
